.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "IWC" "1" "February 2015" "" "iwc Manual"
.
.SH "NAME"
\fBiwc\fR \- Interactive lines count
.
.SH "SYNOPSIS"
\fBiwc\fR
.
.SH "DESCRIPTION"
The \fBiwc\fR utility displays the number of lines in the standard input\. The number is printed while \fBiwc\fR counts all lines, instead of just displaying the total number at the end\.
.
.SH "AUTHOR"
Written by Baptiste Fontaine <\fIb@ptistefontaine\.fr\fR>\.
.
.SH "BUGS"
Bugs should be reported at \fIhttps://github\.com/bfontaine/iwc/issues\fR\.
.
.SH "SEE ALSO"
The project homepage is at \fIhttps://github\.com/bfontaine/iwc\fR\.
